hgrecco/pint-pandas

- .travis.yml
- pint_pandas/__init__.py
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_interface.py
Fixes https://github.com/hgrecco/pint-pandas/issues/21
> Fix offset units

- .travis.yml
- pint_pandas/__init__.py
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_interface.py
Trying to get tests to green before any other changes, but there's one that's passing on my machine but not on travis..
> Mark tests failing due to iter issues

- .travis.yml
- pint_pandas/__init__.py
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_interface.py
Fixes https://github.com/hgrecco/pint-pandas/issues/45
> Reimplement Reduce (Series.min, max..)

- CHANGES
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_interface.py
> Fix tests continued

- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_interface.py
> Only allow floats as magnitudes

- CHANGES
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_interface.py
> Default ureg

- notebooks/pandas_support.ipynb
> import pint_pandas added to notebook example

- bors.toml
> Put all CI status to checkfor as % means any, not all

- .github/workflows/ci.yml
- bors.toml
> Put all ci status within one dummy file to make it easier to use bors

- README.rst
> Fix notebook link

- CHANGES
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_issues.py
> PintArray from Quantity arrays directly

- README.rst
> Add url for pint in README

- .github/workflows/ci.yml
- pint_pandas/testsuite/test_pandas_interface.py
> uprev pandas to 1.3

- .pre-commit-config.yaml
- CHANGES
- notebooks/pint-pandas.ipynb
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_interface.py
Updates notebook to show plotting in pandas 1.3
Adds a line in the notebook documenting https://github.com/hgrecco/pint-pandas/pull/104
>  update notebook

- CHANGES
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_issues.py
> fix offset unit printing

- CHANGES
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_issues.py
> fix pint[]

- .pre-commit-config.yaml
> new flake8 url

- pint_pandas/testsuite/test_issues.py
- pint_pandas/testsuite/test_pandas_extensiontests.py
> cleanup tests

- .github/workflows/ci.yml
> freeze pd 1.5.2

- .github/workflows/ci-pint-master.yml
- .github/workflows/ci-pint-pre.yml
- pint_pandas/pint_array.py
> Get CI working again

- .github/workflows/ci.yml
> test pandas 2.0.2

- .github/workflows/ci-pint-master.yml
- .github/workflows/ci-pint-pre.yml
- .github/workflows/ci.yml
- CHANGES
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_extensiontests.py
> Add accumulate

- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_extensiontests.py
> fix pandas v2.1 NumpyEADtype issue

- docs/getting/index.rst
Fix a simple typo, and see whether my account permissions allow the docs to build correctly on readthedocs.io
> Fix typo (and test readthedocs.io build)

- README.rst
- docs/index.rst
> update readme link

- docs/getting/tutorial.rst
> Fix typo in tutorial.rst

- .github/workflows/ci-pint-master.yml
- docs/user/reading.rst
- notebooks/pint-pandas.ipynb
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_interface.py
> update ci master version

- .github/workflows/ci.yml
- pint_pandas/testsuite/test_pandas_extensiontests.py
> Update tests to import single class from pandas

- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_extensiontests.py
> Change __abs__ to return a PintArray

- pint_pandas/pint_array.py
> Remove print statement

- docs/user/common.rst
> #256 Added new Documentation Section

- .pre-commit-config.yaml
- CHANGES
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_issues.py
- pint_pandas/testsuite/test_pandas_extensiontests.py
- pyproject.toml
> array_function

- pint_pandas/pint_array.py
- <https://en.wiktionary.org/wiki/separator>
> spell 'seperator' -> 'separator'

- .github/workflows/ci-check-dependencies.yml
- .github/workflows/ci-pandas-pre.yml
- .github/workflows/ci-pint-master.yml
- .github/workflows/ci-pint-pre.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/lint-autoupdate.yml
- CHANGES
- docs/user/reading.rst
- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_pandas_interface.py
> parse single row headers

- pint_pandas/pint_array.py
- pint_pandas/testsuite/test_issues.py
> groupby op
